package org.eclipse.hawkbit.ui.common.event;

public enum EventLayout {
    TARGET_TAG_FILTER, TARGET_LIST, DS_LIST, DS_TAG_FILTER, ACTION_HISTORY_LIST, ACTION_HISTORY_STATUS_LIST, ROLLOUT_LIST, ROLLOUT_GROUP_LIST, ROLLOUT_GROUP_TARGET_LIST, TARGET_FILTER_QUERY_LIST, TARGET_FILTER_QUERY_FORM, DS_TYPE_FILTER, SM_TYPE_FILTER, SM_LIST, ARTIFACT_LIST;
}
